# Generated by Django 5.2.4 on 2025-07-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('address', models.TextField()),
                ('profilbio', models.TextField()),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
    ]
