# Generated by Django 5.2.4 on 2025-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_member_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyment',
            fields=[
                ('mpid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('cardno', models.CharField(max_length=255)),
                ('carddate', models.CharField(max_length=255)),
                ('secucode', models.CharField(max_length=255)),
            ],
        ),
    ]
