# Generated by Django 5.2.4 on 2025-07-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
