# Generated by Django 5.2.4 on 2025-07-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cusername', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('bwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blogwrite')),
            ],
        ),
    ]
