# Generated by Django 5.2.4 on 2025-07-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
