# Generated by Django 5.2.4 on 2025-07-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_blogwrite_username_blogwrite_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwrite',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='home.profile'),
        ),
        migrations.AlterField(
            model_name='save',
            name='susername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
