# Generated by Django 5.2.4 on 2025-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwrite',
            name='cimage',
            field=models.ImageField(null=True, upload_to='bimages/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='uimages/'),
        ),
    ]
