# Generated by Django 5.2.4 on 2025-08-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_blogwrite_cimage_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
