# Generated by Django 5.2.4 on 2025-08-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_contect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
